name: Build, Push and Deploy nextjs-deploy client

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
  CONTAINER: nextjs-deploy-test
  TAG: "1.0.0"
  PORT: 55102

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.TAG }}

  deploy:
    name: Deploy to server
    needs: [push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login to the GitHub Packages Docker Registry
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Stop deployed container
        continue-on-error: true
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker stop ${{ env.CONTAINER }}"

      - name: Remove deployed container
        continue-on-error: true
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker rm -v ${{ env.CONTAINER }}"

      - name: Pull latest container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.TAG }}"

      - name: Delete unused images
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker image prune"

      - name: Start docker container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -p ${{ env.PORT }}:3000 --name=${{ env.CONTAINER }} --network=caddy-net -d --restart always ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.TAG }}"

      - name: Logout from the GitHub Packages Docker Registry
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker logout ${{ env.REGISTRY }}"